### ISSUE TITLE
Add ftp endpoint

### ISSUE THREAD

**Issue by igorsyl** [yegor256/s3auth#213]
For buckets with many files it is difficult to download all files using the web front end.
It would be easier to manage larger number of files with an ftp front end.

**Comment by carlosmiranda** [comment]
@davvd Please reassign someone else, sorry.

**Comment by davvd** [comment]
> @davvd Please reassign someone else, sorry.

@carlosmiranda no problem, I'll try to find somebody else

**Comment by davvd** [comment]
@pinaf can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here... The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by pinaf** [comment]
@yegor256 whn you told carlosmiranda to
>Create a test that will use a real FTP client and will try to do a few basic FTP commands

Did you mean to call an external system process (FTP client) or use a java library that implements the FTP protocol?

**Comment by yegor256** [comment]
@pinaf I meant some java library, of course

**Comment by pinaf** [comment]
@yegor256 I can't access the ftp server with the credentials you gave to carlosmiranda.

```
ftp> open maven.s3auth.com
Connected to relay.s3auth.com.
220 (vsFTPd 2.3.5)
Name (maven.s3auth.com): s3auth
331 Please specify the password.
Password:
530 Login incorrect.
Login failed.
```
Using this comment
```
OPEN ftp://maven.s3auth.com
USER s3auth s3auth
CD apidocs
LIST
GET index.html
QUIT
```

**Comment by yegor256** [comment]
@pinaf I don't remember I gave that... anyway, it's a production server, you can't access it just like that. and this FTP functionality is not implemented. I don't understand what you're trying to do...

**Comment by pinaf** [comment]
@yegor256 I was just trying to create a simple test using the apache commons-net library with that sequence of events.

**Comment by yegor256** [comment]
@pinaf but in order these commands to work you should implement FTP server functionality inside s3auth :)

**Comment by pinaf** [comment]
@yegor256 For the time being I created the test pointing to ftp.gnu.org - it downloads a README file and performs a few checks. However, I confess I'm rather confused about what is being requested here. s3auth is a HTTP gateway from what I can tell - are you requesting the implementation of FTP server functionality? If so, I need more information, such as which port it will listen on. I guess the way to do it would be to implement an FTPFacade, analogous to the HTTPFacade, listening on a different port. Probably what I should do here is open a new ticket requesting the information I need, correct?

**Comment by yegor256** [comment]
@pinaf you understood it correctly. we need an `FTPFacade`, similar to `HTTPFacade`. You can submit a new ticket, but keep in mind that tickets don't request information, they complain about incomplete documentation. So far we don't have any documentation about FTP. Nothing to complain about, yet.

**Comment by pinaf** [comment]
@davvd please see PR #264

**Comment by pinaf** [comment]
@davvd merged :)

**Comment by yegor256** [comment]
@pinaf ask the reporter to close it

**Comment by pinaf** [comment]
@igorsyl could you please close this issue?

**Comment by davvd** [comment]
It's closed now

**Comment by pinaf** [comment]
@davvd oh thanks!

**Comment by davvd** [comment]
6 puzzles were created here: `213-2f9b789a`, `213-d22cf12f`, `213-5796b8fa`, `213-6939d515`, `213-721856fe`, `213-af390358`

**Comment by pinaf** [comment]
@davvd could you please end this one?

**Comment by pinaf** [comment]
@davvd any chance we can wrap this up?

**Comment by pinaf** [comment]
@davvd hello???

**Comment by davvd** [comment]
@pinaf **30 mins** sent to your balance (ID `AP-87D95476261313446`), many thanks!

+30 added to your rating, at the moment it is: [+600](http://www.netbout.com/b/35128?open=rating)

**Comment by pinaf** [comment]
@davvd thank you.

**Comment by davvd** [comment]
@igorsyl last 6 puzzles originated from here are solved: `213-2f9b789a`/#289, `213-d22cf12f`/#284, `213-5796b8fa`/#288, `213-6939d515`/#287, `213-721856fe`/#286, `213-af390358`/#285

**Comment by 0pdd** [comment]
@igorsyl 6 puzzles [#391](https://github.com/yegor256/s3auth/issues/391), [#392](https://github.com/yegor256/s3auth/issues/392), [#393](https://github.com/yegor256/s3auth/issues/393), [#394](https://github.com/yegor256/s3auth/issues/394), [#395](https://github.com/yegor256/s3auth/issues/395), [#396](https://github.com/yegor256/s3auth/issues/396) are still not solved.

**Comment by 0pdd** [comment]
@igorsyl 6 puzzles [#355](https://github.com/yegor256/s3auth/issues/355), [#356](https://github.com/yegor256/s3auth/issues/356), [#357](https://github.com/yegor256/s3auth/issues/357), [#359](https://github.com/yegor256/s3auth/issues/359), [#360](https://github.com/yegor256/s3auth/issues/360), [#565](https://github.com/yegor256/s3auth/issues/565) are still not solved; solved: [#358](https://github.com/yegor256/s3auth/issues/358).
