### ISSUE TITLE
DefaultDynamo.java:64-64: Would be nice to migrate...

### ISSUE THREAD

**Issue by davvd** [yegor256/s3auth#90]
Puzzle `1-f2c33b38` in `s3auth-hosts/src/main/java/com/s3auth/hosts/DefaultDynamo.java:64-64` has to be resolved: Would be nice to migrate to jcabi-dynamo

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by davvd** [comment]
@dpisarenko this task is in your hands for 7 days already

-5 added to your rating, at the moment it is: [+160](http://www.netbout.com/b/35089?open=rating)

**Comment by dpisarenko** [comment]
@davvd Please find a reviewer for the pull request https://github.com/yegor256/s3auth/pull/239 .

**Comment by davvd** [comment]
@dpisarenko please don't touch this task, someone else will pick it up, thanks

**Comment by davvd** [comment]
@peterarsentev please go ahead with this task, it's yours

**Comment by davvd** [comment]
@peterarsentev you've been working with this task for too long. I'm sorry, but I'll assign someone else. Please stop working with it. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle... -60 to your rating, your total score is [-135](http://www.netbout.com/b/35098?open=rating)

**Comment by davvd** [comment]
@pinaf can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here. This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by pinaf** [comment]
@davvd @yegor256 regarding carlosmiranda's point number one above:

>Am I right in thinking that we can replace DefaultDynamo's Client field and replace it with Region?

Should I also get rid of the now unused interface `Dynamo.Client`?

**Comment by yegor256** [comment]
@pinaf yes, I think @carlosmiranda is right and we can get rid of `Dynamo.Client`

**Comment by yegor256** [comment]
@pinaf a better approach would be to report a separate ticket for that, saying that we have a redundant class and should remove it, etc.

**Comment by pinaf** [comment]
@yegor256 if I report it you have to pay me then pay someone else to delete those 3 lines. the only problem I see is if another project uses it.

**Comment by yegor256** [comment]
@pinaf that's how we work :) every time you see an issue, don't rush to fix it yourself, better report a bug, see http://www.yegor256.com/2015/01/15/how-to-cut-corners.html

**Comment by pinaf** [comment]
@yegor256 if you insist :) on another note, `s3auth-hosts` does not have a `MANIFEST.MF` file. Should I copy it from `s3auth-relay`?

**Comment by yegor256** [comment]
@pinaf I don't insist. You just won't be able to work otherwise. This is your way to make more money with us - by finding and reporting bugs. If you don't do this, you will make too little and will loose motivation. So, it's important to think the way the article explains.

I didn't get the question about manifest.mf.

**Comment by pinaf** [comment]
@yegor256 in project `s3auth` there is a subfolder called `s3auth-hosts` which contains the code we are talking about (DefaultDynamo, Dynamo, etc). `DefaultDynamo` makes references to properties within a MANIFEST file which does not exist in `s3auth-hosts` but does exist in subfolder `s3auth-relay`. If you try to instantiante a `DefaultDynamo` with the default constructor it will fail because it cannot find the manifest. Should I copy the manifest from `s3auth-relay` into `s3auth-hosts` ?

**Comment by yegor256** [comment]
@pinaf you have another alternative?

**Comment by pinaf** [comment]
@yegor256 forget it. it's a separete issue. i'll report as an issue.

**Comment by pinaf** [comment]
@davvd @yegor256 bug report: #260

**Comment by pinaf** [comment]
@yegor256 @davvd quick question: the methods `add`, `load`, `remove` in `DefaultDynamo` call `shutdown` on the amazon client when done but this cannot be done with the new `MkRegion` mock class. Should I remove the shutdown calls?

**Comment by pinaf** [comment]
#7 is necessary for the new test with `H2Data`.

**Comment by yegor256** [comment]
@pinaf try to avoid asking technical questions in the same ticket as the task. Every time you have a question, it's a sign that existing documentation is incomplete. Submit a new bug and improve it. By asking here and getting an answer you're not helping the project. You will solve the problem, close the ticket and in a few weeks someone else will ask the same question. It's waste of time and money. Better, ask us to fix the documentation and improve the code base. See more details here http://www.yegor256.com/2015/01/15/how-to-cut-corners.html

**Comment by pinaf** [comment]
@yegor256 got it. still getting used to this methodology :)

**Comment by pinaf** [comment]
@davvd please see PR #261

**Comment by davvd** [comment]
The task is closed, thanks everybody

**Comment by davvd** [comment]
@pinaf it's not yours any more,because it took too long,please stop working with it. -60 to your rating, your total score is [+255](http://www.netbout.com/b/35128?open=rating). you're working with this issue for 9 days already. do not forget to remove the TODO puzzle from the source code. -30 added to your rating, current score is: [+225](http://www.netbout.com/b/35128?open=rating)

**Comment by yegor256** [comment]
@davvd I think we're wrong here, add extra 30 mins to @pinaf pls

**Comment by davvd** [comment]
my bad, should be open. I'll remove the negative rating too.

**Comment by pinaf** [comment]
@davvd OK. Keep in mind you subtracted 90 points.

**Comment by pinaf** [comment]
@davvd can we get this fixed?

**Comment by yegor256** [comment]
@pinaf it's fixed, I removed the points

**Comment by pinaf** [comment]
@yegor256 points are correct but task disappeared from agenda.

**Comment by yegor256** [comment]
@davvd assign @pinaf back to this task pls

**Comment by davvd** [comment]
> @davvd assign @pinaf back to this task pls

@yegor256 OK @pinaf please proceed, this task is yours

**Comment by pinaf** [comment]
@davvd thank you. Still impeded by https://github.com/jcabi/jcabi-dynamo/issues/28

**Comment by davvd** [comment]
> @davvd we need more time here

@yegor256 of course, take your time

**Comment by pinaf** [comment]
@yegor256 @davvd the issue was closed with just a test implemented. functionality still isn't there so we still need to wait for the actual implementation in a new issue.

**Comment by pinaf** [comment]
@davvd merged. please close if alright.

**Comment by longtimeago** [comment]
@davvd close the issue, please

**Comment by pinaf** [comment]
@davvd please close the issue man..

**Comment by pinaf** [comment]
@davvd seriously. what is going on? why don't you close the issue?

**Comment by davvd** [comment]
once `90-43f9c549` puzzle is resolved (later, in another ticket), this ticket will be fully complete

**Comment by pinaf** [comment]
@davvd close the issue

**Comment by davvd** [comment]
Done, thanks all, closing..

**Comment by davvd** [comment]
@pinaf **30 mins** sent to your balance (ID `AP-937875029L175551X`), many thanks!

+30 added to your rating, current score is: [+2201](http://www.netbout.com/b/35128?open=rating)

**Comment by davvd** [comment]
@yegor256 last puzzled solved `90-43f9c549`/#292

**Comment by 0pdd** [comment]
@davvd the puzzle [#390](https://github.com/yegor256/s3auth/issues/390) is still not solved.

**Comment by 0pdd** [comment]
@davvd the only puzzle [#352](https://github.com/yegor256/s3auth/issues/352) is solved here.
